name: Publish Website
on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
env:
  IMAGE_NAME: mojolicious.org
jobs:
  push:
    runs-on: ubuntu-latest
    environment: Build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: jberger/action-install-kubectl@master
        with:
          kube_config_data: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for container
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          context: .
          no-cache: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Rollout
        run: |
          kubectl rollout restart deployment mojolicious-org && kubectl rollout status deployment mojolicious-org
